"""Add automated_followup and automated_reply to OutreachAttempt

Revision ID: 158e194817c3
Revises: cb72bf733cd1
Create Date: 2024-10-05 19:54:04.022813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158e194817c3'
down_revision = 'cb72bf733cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automated_followup', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('automated_reply', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_attempt', schema=None) as batch_op:
        batch_op.drop_column('automated_reply')
        batch_op.drop_column('automated_followup')

    # ### end Alembic commands ###
