"""Add author_name and author_email to Website model

Revision ID: 5140277a1cad
Revises: e501743f5a51
Create Date: 2024-09-27 16:41:10.599180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5140277a1cad'
down_revision = 'e501743f5a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('author_email', sa.String(length=320), nullable=True))
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=320), nullable=True))
        batch_op.drop_column('author_email')
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
