"""empty message

Revision ID: 64abf066597c
Revises: 158e194817c3
Create Date: 2024-10-06 14:11:47.178635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64abf066597c'
down_revision = '158e194817c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_email_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_attempt', schema=None) as batch_op:
        batch_op.drop_column('cached_email_content')

    # ### end Alembic commands ###
