"""empty message

Revision ID: 81d4d54466df
Revises: d299b9eda009
Create Date: 2024-10-16 21:24:42.306803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d4d54466df'
down_revision = 'd299b9eda009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('press_release_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('press_release_content', sa.Text(), nullable=True))
        batch_op.alter_column('target_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Default Keyword'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Default Keyword'"))
        batch_op.alter_column('target_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('press_release_content')
        batch_op.drop_column('press_release_url')
        batch_op.drop_column('topic')
        batch_op.drop_column('campaign_type')

    # ### end Alembic commands ###
