"""Update User model and add Campaign and OutreachAttempt

Revision ID: 8fc7089951a2
Revises: 374201d4f9da
Create Date: 2024-10-03 17:04:59.723260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8fc7089951a2'
down_revision = '374201d4f9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('company_profile', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company_profile')
        batch_op.drop_column('company')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email_provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email_settings', sqlite.JSON(), nullable=True),
    sa.Column('company', sa.VARCHAR(length=120), nullable=False),
    sa.Column('company_profile', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
