"""Add automated_reply_enabled to Website

Revision ID: 91c61a45a359
Revises: 5140277a1cad
Create Date: 2024-10-01 20:58:13.266475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c61a45a359'
down_revision = '5140277a1cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email_provider', sa.String(length=50), nullable=True),
    sa.Column('email_settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('response')

    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automated_reply_enabled', sa.Boolean(), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=2083),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('domain_authority',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('author_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('author_email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.alter_column('author_email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=320),
               existing_nullable=True)
        batch_op.alter_column('author_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('domain_authority',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=2083),
               existing_nullable=False)
        batch_op.drop_column('automated_reply_enabled')

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.TEXT(), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('email_type')

    op.drop_table('user')
    # ### end Alembic commands ###
