"""Add name column to Campaign model

Revision ID: ca5a5673bdd1
Revises: dc8d5019ce27
Create Date: 2024-10-05 11:02:19.942736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5a5673bdd1'
down_revision = 'dc8d5019ce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default='Default Campaign Name'))
        batch_op.add_column(sa.Column('keyword', sa.String(length=100), nullable=False, server_default='Default Keyword'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('keyword')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
