"""Add PR campaign fields and update existing structure

Revision ID: d12fbf00eade
Revises: 81d4d54466df
Create Date: 2024-10-16 21:29:35.204620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12fbf00eade'
down_revision = '81d4d54466df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_type', sa.String(length=50), nullable=False, server_default='seo'))
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('press_release_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('press_release_content', sa.Text(), nullable=True))
        batch_op.alter_column('target_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('target_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('press_release_content')
        batch_op.drop_column('press_release_url')
        batch_op.drop_column('topic')
        batch_op.drop_column('campaign_type')
    # ### end Alembic commands ###
