"""Fix User-Campaign relationship

Revision ID: d1b387da2c93
Revises: 8b6e860928a9
Create Date: 2024-10-13 20:07:27.604485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b387da2c93'
down_revision = '8b6e860928a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('target_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Default Keyword'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Default Keyword'"))
        batch_op.alter_column('target_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
