"""Add title and snippet to Website model

Revision ID: f5968b5c951f
Revises: d1b387da2c93
Create Date: 2024-10-13 20:38:29.984762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5968b5c951f'
down_revision = 'd1b387da2c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('snippet', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('snippet')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
